### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by vaishnavigour** [vaishnavigour/DSA-Syllabus#2]
- [x]  Complete Git & GitHub Course
- [x] Introduction to Programming
  - [x] Types of languages
  - [x] Memory management
- [x] Flow of the program
  - [x]  Flowcharts
   - [x] Pseudocode
- [x] Introduction to Java
  - [x] Introduction
  - [x]  How it works
  - [x] Setup Installation
  - [x] Input and Output in Java
  - [x] Conditionals & Loops in Java
    - [x]  if else
    - [x]  loops
    - [x]  Switch statements
  - [x]  Data types
  - [x] Coding best practices
- [x] Functions
  - [ ]  Introduction
  - [ ] #4
  - [ ]  Shadowing
  - [ ] Variable Length Arguments
  - [ ] Overloading
- [x]  Arrays
  - [x] Introduction
  - [x] Memory management
  - [x] Input and Output
  - [x] ArrayList Introduction
  - [ ] Sorting
     - [ ] Insertion Sort
     - [ ] Selection Sort
     - [ ] Bubble Sort
     - [ ] Cyclic Sort
     - [ ] (More ahead)
  - [ ] Searching
    - [x] Linear Search
    - [x] Binary Search
     - [ ] Modified Binary Search
    - [x] Binary Search on 2D Arrays
  - [ ] Sliding window
  - [x] Two Pointer
  - [ ] Subarray Questions
  - [ ] Kadane's Algorithm
  - [ ] Pattern questions
- [x] Strings
  - [x] Introduction
  - [x] How Strings work
  - [x] Comparison of methods
  - [x] Operations in Strings
  - [x] StringBuilder in java
- [ ] Maths for DSA
  - [ ] Introduction
  - [ ] Complete Bitwise Operators
  - [ ]  Prime numbers
  - [ ]  HCF / LCM
  - [ ] Sieve of Eratosthenes
  - [ ] Newton's Square Root Method
  - [ ] Number Theory
   - [ ] Euclidean algorithm
  - [ ]  Modulo Properties (of -ve also)
  - [ ]  Advanced Concepts for CP (later in the course)
    - [ ]  Bitwise + DP
    - [ ] Extended Euclidean algorithm
    - [ ] Modulo Multiplicative Inverse
    - [ ] Linear Diophantine Equations
    - [ ] Fermat’s Theorem
    - [ ] Wilson's Theorem
    - [ ] Lucas Theorem
    - [ ] Chinese Remainder Theorem
- [x] Recursion
  - [ ] Introduction
  - [ ] Why recursion?
  - [ ] Flow of recursive programs stacks
  - [ ] Convert recursion to iteration
  - [ ] Tree building of function calls
  - [ ] Tail recursion
  - [ ] Sorting:
    - [ ] Merge Sort
    - [ ] Quick Sort
  - [ ] Backtracking
    - [ ] Sudoku Solver
    - [ ] N Queens
    - [ ] N Knights
    - [ ] Maze problems
  - [ ] Recursion String Problems
  - [ ] Recursion Array Problems
  - [ ] Recursion Pattern Problems
  - [ ] Subset Questions
- [x] Space and Time Complexity Analysis
  - [ ] Introduction
  - [ ] Comparisons of various cases
  - [ ] Solving Linear Recurrence Relations
  - [ ] Solving Divide and Conquer Recurrence Relations
  - [ ] Big O, Big Omega, Big Theta Notations
  - [ ] Get equation of any relation easily best and easiest approach
  - [ ] Complexity discussion of all the problems we do
  - [ ] Space Complexity
  - [ ] Memory Allocation of various languages
  - [ ] NP Completeness and Hardness
- [x] Object Oriented Programming
  - [x] Introduction
  - [x] Classes & its instances
  - [x] this keyword in Java
  - [x] Properties
    - [x] Inheritance
    - [x] Abstraction
    - [x] Polymorphism
    - [x] Encapsulation
  - [x] Overloading & Overriding
  - [x] Static & Non Static
  - [x] Access Control
  - [x] Interfaces
  - [x] Abstract Classes
  - [ ] Singleton Class
  - [ ] final, finalize, finally
  - [ ] Object Class
  - [ ] Generics
  - [ ] Exception Handling
  - [ ] Collections Framework
  - [ ] Lambda Expression
  - [ ] Enums
  - [ ] Fast IO
  - [ ] File handling 
- [ ] Greedy Algorithms
- [ ] Stacks & Queues
  - [ ] Introduction
  - [ ] Interview problems
  - [ ] Push efficient
  - [ ] Pop efficient
  - [ ] Queue using Stack and Vice versa
  - [ ] Circular Queue
- [ ] Linked List
  - [ ] Introduction
  - [ ] Fast and slow pointer
  - [ ] Cycle Detection
  - [ ] Single and Doubly LinkedList
  - [ ] Reversal of LinkedList
- [ ] Dynamic Programming
  - [ ] Introduction
  - [ ] Recursion + Recursion DP + Iteration + Iteration Space Optimized
  - [ ] Complexity Analysis
  - [ ] 0/1 Knapsack
  - [ ] Subset Questions
  - [ ] Unbounded Knapsack
  - [ ] Subsequence questions
  - [ ] String DP
- [ ] Trees
  - [ ] Introduction
  - [ ] Binary Trees
  - [ ] Binary Search Trees
  - [ ] DFS
  - [ ] BFS
  - [ ] AVL Trees
  - [ ] Segment Tree
  - [ ] Fenwick Tree / Binary Indexed Tree
- [ ] Square Root Decomposition
- [ ] Heaps
  - [ ] Introduction
  - [ ] Theory
  - [ ] Priority Queue
  - [ ] Heapsort
  - [ ] Two Heaps Method
  - [ ] k way merge
  - [ ] Top k elements
  - [ ] Interval problems
- [ ] HashMap
  - [ ] Introduction
  - [ ] Theory how it works
  - [ ] Comparisons of various forms
  - [ ] Limitations and how to solve
  - [ ] Map using LinkedList
  - [ ] Map using Hash
  - [ ] Count Sort
  - [ ] Radix Sort
  - [ ] Chaining
  - [ ] Probing
  - [ ] Huffman Encoder
- [ ] Tries
- [ ] Graphs
  - [ ] Introduction
  - [ ] BFS
  - [ ] DFS
  - [ ] Working with graph components
  - [ ] Minimum Spanning Trees
  - [ ] Kruskal Algorithm
  - [ ] Prims Algorithm
  - [ ] Dijkstra’s shortest path algorithm
  - [ ] Topological Sort
  - [ ] Bellman ford
  - [ ] A* pathfinding Algorithm
